name: car_marketplace
description: "A new Flutter project."
publish_to: 'none'

version: 1.0.0+1

environment:
  sdk: ^3.7.0

dependencies:
  flutter:
    sdk: flutter
  supabase_flutter: ^2.9.1        
  image_picker: ^1.1.2           
  file_picker: ^10.2.0               
  video_player: ^2.7.1              
  path_provider: ^2.1.5          
  cupertino_icons: ^1.0.8
  go_router: ^16.0.0
  logger: ^2.6.1
  intl: ^0.20.2
  uuid: ^4.5.1
  collection: ^1.19.1
  url_launcher: ^6.3.2
  google_maps_flutter: ^2.13.1
  geolocator: ^14.0.2

dev_dependencies:
  flutter_test:
    sdk: flutter
  flutter_lints: ^5.0.0

flutter:
  uses-material-design: true